-- Sample data for Internal Risk Engine Service

-- Sample loan applications
INSERT INTO loan_applications (
    applicant_name, email, age, annual_income, loan_amount, loan_type, 
    loan_term_months, credit_score, employment_years, monthly_debt_payments, 
    down_payment, has_collateral, collateral_value, created_at, updated_at
) VALUES 
(
    'John Smith', 'john.smith@email.com', 35, 75000.00, 25000.00, 'PERSONAL',
    60, 720, 5, 1200.00, 0.00, false, null, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'Sarah Johnson', 'sarah.johnson@email.com', 28, 95000.00, 350000.00, 'MORTGAGE',
    360, 750, 3, 800.00, 70000.00, true, 420000.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'Mike Brown', 'mike.brown@email.com', 42, 60000.00, 30000.00, 'AUTO',
    72, 680, 8, 1500.00, 5000.00, true, 35000.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'Emily Davis', 'emily.davis@email.com', 25, 45000.00, 15000.00, 'STUDENT',
    120, 650, 1, 300.00, 0.00, false, null, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
),
(
    'Robert Wilson', 'robert.wilson@email.com', 38, 120000.00, 100000.00, 'BUSINESS',
    84, 700, 10, 2500.00, 20000.00, true, 150000.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- Sample risk assessments (these would normally be generated by the API)
INSERT INTO risk_assessments (
    loan_application_id, risk_score, risk_level, approval_recommendation,
    recommended_interest_rate, debt_to_income_ratio, loan_to_value_ratio,
    credit_score_factor, income_factor, employment_factor, collateral_factor,
    loan_type_factor, assessment_notes, created_at
) VALUES 
(
    1, 275, 'LOW', true, 9.50, 0.1920, 1.0000,
    100, 75, 50, 150, 150,
    'Risk Assessment Summary:
- Overall Risk Score: 275 (Low Risk)
- Excellent credit score (720)
- Unsecured loan increases risk',
    CURRENT_TIMESTAMP
),
(
    2, 225, 'LOW', true, 5.50, 0.1053, 0.8333,
    50, 50, 100, 25, 50,
    'Risk Assessment Summary:
- Overall Risk Score: 225 (Low Risk)
- Excellent credit score (750)
- Loan secured with collateral',
    CURRENT_TIMESTAMP
),
(
    3, 350, 'MODERATE', true, 6.00, 0.3000, 0.8571,
    150, 100, 50, 50, 75,
    'Risk Assessment Summary:
- Overall Risk Score: 350 (Moderate Risk)
- Loan secured with collateral',
    CURRENT_TIMESTAMP
),
(
    4, 400, 'MODERATE', true, 7.00, 0.0800, 1.0000,
    150, 75, 150, 150, 100,
    'Risk Assessment Summary:
- Overall Risk Score: 400 (Moderate Risk)
- Unsecured loan increases risk',
    CURRENT_TIMESTAMP
),
(
    5, 275, 'LOW', true, 8.00, 0.2500, 0.8000,
    100, 50, 50, 50, 125,
    'Risk Assessment Summary:
- Overall Risk Score: 275 (Low Risk)
- Loan secured with collateral',
    CURRENT_TIMESTAMP
);
